### ISSUE TITLE
More on Jupyter notebooks

### ISSUE THREAD

**Issue by klieret** [klieret/everything-you-didnt-now-you-needed#8]
Also note that jupytext allows you to run all static checkers on them.

Point out that you can get most IDEs to talk Jupyter to get more static insight

**Comment by henryiii** [comment]
Also there's a tool that allows various tooling to run on notebooks. I don't remember what it was, I mostly used it for black then black started supporting notebooks natively.

**Comment by klieret** [comment]
Oh, interesting, that would be quite useful. 

I only found various versions of static checkers like `flake8-nb`, the `black` extension, etc. 
Obviously, if you just want to check things, you can always convert && check

With jupyter notebooks being everywhere in data science, I think this might even be worth a full talk/deck of slides just to address all these things...

**Comment by henryiii** [comment]
@matthewfeickert might remember it? I’ve still got it somewhere, but don’t remember where.

**Comment by henryiii** [comment]
Found it on Hist: https://github.com/nbQA-dev/nbQA

**Comment by matthewfeickert** [comment]
Ah I thought you were talking about https://github.com/Nikoleta-v3/blackbook. Yeah, we still [use nbQA in `pyhf` for `nbqa-pyupgrade`](https://github.com/scikit-hep/pyhf/blob/97664bcfcef3b4a459a7f700b0703b40aec9b842/.pre-commit-config.yaml#L62-L66).
